#!c:/ruby/bin/ruby.exe
require 'rubygems'
require 'rubygems/gem_runner'
require 'rubygems/exceptions'

def install(lib)
  begin
    Gem::GemRunner.new.run ['install', lib]
  rescue Gem::SystemExitException => e
  end
end

puts "Installing required dependencies"

install 'aws-s3'

puts "Checking dependencies"
require 'aws/s3'
